---
# Tasks related to installation of Oracle Java distribution
#

- name: Ensure Java installation directory exists
  tags: java
  file:
        path={{ java_oracle_install_target_dir }}
        state=directory
        mode=0755
        recurse=yes

- name: Check whether distribution installation exists
  stat:
        path={{ java_oracle_install_dir }}
  register: distribution_installation

- name: Unarchive Java distribution
  tags: java
  register: unarchived_distribution
  unarchive:
        dest={{ java_oracle_install_target_dir }}
        src={{ java_oracle_download_dir }}/{{ java_oracle_distribution }}-{{ java_oracle_version }}-linux-x64.tar.gz
        copy=no
  when: distribution_installation.stat.exists == False

- name: Extract Java path name from extract
  ls:
        path={{ java_oracle_install_target_dir }}
        filter={{ java_oracle_distribution }}*
        result=first
  register: installation_dir_content

- debug: var=installation_dir_content

- name: Link extracted directory to expected installation path
  file:
        src={{ java_oracle_install_target_dir }}/{{ installation_dir_content.content }}
        dest={{ java_oracle_install_dir }}
        state=link

