---
# Main list of tasks to be executed.
#
#   Fail the play if it runs on an unsupported platform,
- name: Assert platform is supported
  tags: java
  assert:
    that:
      - ansible_os_family in ['RedHat', 'Debian']
      - ansible_architecture in ['x86_64']

- include: download.yml
  tags:
    - java

- include: install.yml
  tags:
    - java